select * from customer limit 20

--Q1. What is the total revenue generated by male vs. female customers?
select "Gender", SUM("Purchase Amount (USD)") as revenue
from customer
group by "Gender";

--Q2. Which customers used a discount but still spent more than the average purchase amount?

select "Customer ID", "Purchase Amount (USD)"
from customer
where "Discount Applied" = 'Yes'
and "Purchase Amount (USD)" >= (
    select AVG("Purchase Amount (USD)") 
    from customer
);

--Q3. Which are the top 5 products with the highest average review rating?
select "Item Purchased",
       ROUND(AVG("Review Rating")::numeric, 2) as "Average Product Rating"
from customer
group by "Item Purchased"
order by "Average Product Rating" desc
limit 5;

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
select "Shipping Type",
ROUND(AVG("Purchase Amount (USD)"),2)
from customer
where "Shipping Type" in ('Standard','Express')
group by "Shipping Type"


--Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-su
select "Subscription Status",
COUNT("Customer ID") as "Total Customer",
ROUND(AVG("Purchase Amount (USD)"),2) as "Avg Spend",
ROUND(SUM("Purchase Amount (USD)"),2) as "Total Revenue"
from customer
group by "Subscription Status"
order by "Total Revenue","Avg Spend" desc;

--Q6. Which 5 products have the highest percentage of puchases with discounts applied?
select "Item Purchased",
ROUND(100 * SUM(CASE WHEN "Discount Applied"='Yes'THEN 1 ELSE 0 END)/COUNT(*),2) as "Discount Rate"
from customer
group by "Item Purchased"
order by "Discount Rate" desc
limit 5;
--Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and sh
--number of previous purchases, and show the count of each segment.
with "Customer Type" as(
select "Customer ID","Previous Purchases",
CASE
    WHEN "Previous Purchases" = 1 THEN 'New'
	WHEN "Previous Purchases" BETWEEN 2 AND 10 THEN 'Returning'
	ELSE 'Loyal'
	END AS "Customer Segment"
from customer
)

select "Customer Segment", count(*) as "Number Of Customers"
from "Customer Type"
group by "Customer Segment"

--Q8. What are the top 3 most purchased products within each category?
with "Item Counts" as (
    select 
        "Category",
        "Item Purchased",
        COUNT("Customer ID") as "Total Orders",
        ROW_NUMBER() over (
            partition by "Category" 
            order by COUNT("Customer ID") DESC
        ) as "Item Rank"
    from customer
    group by "Category", "Item Purchased"
)

select "Item Rank", "Category", "Item Purchased", "Total Orders"
from "Item Counts"
where "Item Rank" <= 3;

--Q9. Are customers are repeat buyers (more tha 5 previous purchases) also likely to subscribe?
select "Subscription Status",
count("Customer ID")as "Repeat Buyers"
from customer
where "Previous Purchases" > 5
group by "Subscription Status"

--Q10. What is the revenue contribution of each age group?
select "Age",
       SUM("Purchase Amount (USD)") as "Total Revenue"
from customer
group by "Age"
order by "Total Revenue" desc;
